trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
stages:
  - stage: test
    displayName: Test
    jobs:
    - job: check_formatting_test_core
      displayName: Check formatting and test puzzle core
      pool:
        vmImage: ubuntu-16.04
      steps:
        - script: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            echo "##vso[task.setvariable variable=PATH]$PATH:$HOME/.cargo/bin"
          displayName: Install Rust
        - script: |
            rustup component add rustfmt
            cargo fmt -- --check
          displayName: Run rustfmt
        - script: |
            cd eight-puzzle-core
            cargo test --verbose
          displayName: Run core tests.

  - stage: build
    displayName: Build
    jobs:
    - template: ci-script/build_publish_unix.yml
      parameters:
        name: linux
        vmImage: ubuntu-16.04
        rustupToolchain: stable-x86_64-unknown-linux-gnu
        archiveName: eight-puzzle-v1.1-linux-x64.zip

    - template: ci-script/build_publish_unix.yml
      parameters:
        name: osx
        vmImage: macOS-10.13
        rustupToolchain: stable-x86_64-apple-darwin
        archiveName: eight-puzzle-v1.1-osx-x64.zip

    - template: ci-script/build_publish_windows.yml
      parameters:
        name: win32
        vmImage: vs2017-win2016
        rustupToolchain: stable-i686-pc-windows-gnu
        archiveName: eight-puzzle-v1.1-win-x86.zip

    - template: ci-script/build_publish_windows.yml
      parameters:
        name: win64
        vmImage: vs2017-win2016
        rustupToolchain: stable-x86_64-pc-windows-gnu
        archiveName: eight-puzzle-v1.1-win-x64.zip

  - stage: release
    displayName: GitHub Release
    jobs:
    - job: github_release
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: app
          targetPath: "$(Pipeline.Workspace)/app"
        displayName: 'Download artifact'
      - task: GithubRelease@0
        displayName: 'Create GitHub Release'
        inputs:
          gitHubConnection: Jason5Lee GitHub Release
          assets: '$(Pipeline.Workspace)/app/*'
          repositoryName: Jason5Lee/eight-puzzle-rs
          tagSource: manual
          tag: v1.1
