jobs:
  - job: check_formatting_test_core
    displayName: Check formatting and test puzzle core
    pool:
      vmImage: ubuntu-16.04
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH]$PATH:$HOME/.cargo/bin"
        displayName: Install Rust
      - script: |
          rustup component add rustfmt
          cargo fmt -- --check
        displayName: Run rustfmt
      - script: |
          cd eight-puzzle-core
          cargo test --verbose
        displayName: Run core tests.

  - template: ci-script/build_publish_unix.yml
    parameters:
      name: Linux
      vmImage: ubuntu-16.04
      rustupToolchain: stable-x86_64-unknown-linux-gnu
      version: 1.0

  - template: ci-script/build_publish_unix.yml
    parameters:
      name: macOS
      vmImage: macOS-10.13
      rustupToolchain: stable-x86_64-apple-darwin
      version: 1.0

  - template: ci-script/build_publish_windows.yml
    parameters:
      name: Windows
      vmImage: vs2017-win2016
      rustupToolchain32: stable-i686-pc-windows-gnu
      rustupToolchain64: stable-x86_64-pc-windows-gnu
      version: 1.0