[package]
name = "eight-puzzle"
version = "0.1.0"
authors = ["Jason Lee <jason5lee@hotmail.com>"]
edition = "2018"

[[bin]]
name = "eight-puzzle"
path = "src/main.rs"

[dependencies]
piston_window = "0.93"
find_folder = "0.3"
eight-puzzle-core = { path = "../eight-puzzle-core" }