jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    bin_path: ${{ parameters.binPath }}
    rustup_toolchain: ${{ parameters.rustupToolchain }}
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: cargo build --release
    displayName: Build the project
  - ${{ if eq(parameters.name, 'osx') }}:
      - script: |
          cp -R mac_os_app_template "Eight Puzzle.app"
          cp Resources/* "Eight Puzzle.app/Contents/Resources"
          mkdir "Eight Puzzle.app/Contents/MacOS"
          cp target/release/eight-puzzle "Eight Puzzle.app/Contents/MacOS"
        displayName: Generate MacOS App
      - task: CopyFiles@2
        inputs:
          contents: 'Eight Puzzle.app/**/*'
          targetFolder: $(Build.ArtifactStagingDirectory)
        displayName: Copy App File
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: ${{ format('eight-puzzle-{0}-osx', parameters.version) }}
        displayName: Publish
  - ${{ if eq(parameters.name, 'linux') }}:
      - task: CopyFiles@2
        inputs:
          sourceFolder: 'target/release'
          contents: 'eight-puzzle'
          targetFolder: $(Build.ArtifactStagingDirectory)
        displayName: Copy Executable File
      - task: CopyFiles@2
        inputs:
          contents: 'Resources/*'
          targetFolder: $(Build.ArtifactStagingDirectory)
        displayName: Copy Resources
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: ${{ format('eight-puzzle-{0}-linux-x86_64', parameters.version) }}
        displayName: Publish