jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    bin_path: ${{ parameters.binPath }}
    rustup_toolchain: ${{ parameters.rustupToolchain }}
  steps:
  # Linux and macOS.
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: cargo build --release
    displayName: Build the project
  # Linux and macOS.
  - task: CopyFiles@2
    inputs:
      contents: 'target/release'
      targetFolder: $(Build.ArtifactStagingDirectory)/64
    displayName: Copy Release Files
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: ${{ format('{0}{1}', parameters.name, parameters.version) }}
    displayName: Publish