jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    rustup_toolchain: ${{ parameters.rustupToolchain }}
  steps:
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Install rust
  - script: cargo build --release
    displayName: Build the project
  - task: CopyFiles@2
    inputs:
      sourceFolder: 'target/release'
      contents: 'eight-puzzle.exe'
      targetFolder: 'app'
    displayName: Copy Exe File
  - task: CopyFiles@2
    inputs:
      contents: 'Resources/*'
      targetFolder: 'app'
    displayName: Copy Resources
  - task: ArchiveFiles@2
    input:
      rootFolderOrFile: 'app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: "$(Build.ArtifactStagingDirectory)/${{ parameters.archiveName }}"
    displayName: Archive App
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: app
    displayName: Publish